python ../train.py --cfg_file "cfgs/US/GAT.yaml" 
python ../train.py --cfg_file "cfgs/US/GRU_GAT.yaml"
python ../train.py --cfg_file "cfgs/US/GRU.yaml"
python ../train.py --cfg_file "cfgs/US/LSTM.yaml"
python ../train.py --cfg_file "cfgs/US/LSTM_GAT.yaml"
python ../train.py --cfg_file "cfgs/US/RNN.yaml"
python ../train.py --cfg_file "cfgs/US/ST_GraphAttn.yaml"